import type { SampleDataset } from '../types/table';

export const SAMPLE_DATASETS: SampleDataset[] = [
  {
    id: 'products',
    name: 'E-commerce Products',
    description: 'Product catalog with nested ratings, dimensions, tags and pricing.',
    path: '$.products',
    data: {
      status: 'success',
      total: 10,
      skip: 0,
      limit: 10,
      products: [
        {
          id: 1,
          title: 'Essence Mascara Lash Princess',
          category: 'beauty',
          price: 9.99,
          discountPercentage: 7.17,
          rating: 4.94,
          stock: 5,
          tags: ['beauty', 'mascara'],
          brand: 'Essence',
          sku: 'RCH45Q1A',
          weight: 2,
          dimensions: { width: 23.17, height: 14.43, depth: 28.01 },
          warrantyInformation: '1 month warranty',
          availabilityStatus: 'Low Stock',
          returnPolicy: '30 days return policy',
          minimumOrderQuantity: 24,
          inStock: true,
          createdAt: '2024-05-23T08:56:21.618Z',
        },
        {
          id: 2,
          title: 'Eyeshadow Palette with Mirror',
          category: 'beauty',
          price: 19.99,
          discountPercentage: 5.5,
          rating: 3.28,
          stock: 44,
          tags: ['beauty', 'eyeshadow'],
          brand: 'Glamour Beauty',
          sku: 'MVCFJ27F',
          weight: 3,
          dimensions: { width: 12.42, height: 8.63, depth: 29.13 },
          warrantyInformation: '1 year warranty',
          availabilityStatus: 'In Stock',
          returnPolicy: '30 days return policy',
          minimumOrderQuantity: 32,
          inStock: true,
          createdAt: '2024-05-23T08:56:21.618Z',
        },
        {
          id: 3,
          title: 'Powder Canister',
          category: 'beauty',
          price: 14.99,
          discountPercentage: 18.14,
          rating: 3.82,
          stock: 59,
          tags: ['beauty', 'face powder'],
          brand: 'Velvet Touch',
          sku: '9EN8W04T',
          weight: 8,
          dimensions: { width: 24.16, height: 10.7, depth: 11.07 },
          warrantyInformation: '3 months warranty',
          availabilityStatus: 'In Stock',
          returnPolicy: '60 days return policy',
          minimumOrderQuantity: 25,
          inStock: true,
          createdAt: '2024-05-23T08:56:21.618Z',
        },
        {
          id: 4,
          title: 'Red Lipstick',
          category: 'beauty',
          price: 12.99,
          discountPercentage: 19.03,
          rating: 2.51,
          stock: 68,
          tags: ['beauty', 'lipstick'],
          brand: 'Chic Cosmetics',
          sku: 'O5IF1N09',
          weight: 5,
          dimensions: { width: 14.37, height: 13.94, depth: 14.44 },
          warrantyInformation: 'Lifetime warranty',
          availabilityStatus: 'In Stock',
          returnPolicy: '90 days return policy',
          minimumOrderQuantity: 6,
          inStock: true,
          createdAt: '2024-05-23T08:56:21.618Z',
        },
        {
          id: 5,
          title: 'Red Nail Polish',
          category: 'beauty',
          price: 8.99,
          discountPercentage: 2.46,
          rating: 3.91,
          stock: 71,
          tags: ['beauty', 'nail polish'],
          brand: 'Nail Couture',
          sku: 'KO5PHSYD',
          weight: 9,
          dimensions: { width: 8.11, height: 10.89, depth: 29.06 },
          warrantyInformation: '1 year warranty',
          availabilityStatus: 'In Stock',
          returnPolicy: 'No return policy',
          minimumOrderQuantity: 46,
          inStock: true,
          createdAt: '2024-05-23T08:56:21.618Z',
        },
        {
          id: 6,
          title: 'Calvin Klein CK One',
          category: 'fragrances',
          price: 49.99,
          discountPercentage: 0.32,
          rating: 4.85,
          stock: 17,
          tags: ['fragrances', 'perfumes'],
          brand: 'Calvin Klein',
          sku: 'D9046SX2',
          weight: 5,
          dimensions: { width: 11.53, height: 14.44, depth: 6.81 },
          warrantyInformation: '5 year warranty',
          availabilityStatus: 'In Stock',
          returnPolicy: 'No return policy',
          minimumOrderQuantity: 20,
          inStock: true,
          createdAt: '2024-05-23T08:56:21.618Z',
        },
        {
          id: 7,
          title: 'Chanel Coco Noir Eau De',
          category: 'fragrances',
          price: 129.99,
          discountPercentage: 18.64,
          rating: 2.76,
          stock: 41,
          tags: ['fragrances', 'perfumes'],
          brand: 'Chanel',
          sku: 'K7A0ST9N',
          weight: 4,
          dimensions: { width: 21.27, height: 28.0, depth: 11.89 },
          warrantyInformation: '1 year warranty',
          availabilityStatus: 'In Stock',
          returnPolicy: '60 days return policy',
          minimumOrderQuantity: 5,
          inStock: true,
          createdAt: '2024-05-23T08:56:21.618Z',
        },
        {
          id: 8,
          title: 'Dior J\'adore',
          category: 'fragrances',
          price: 89.99,
          discountPercentage: 17.44,
          rating: 3.15,
          stock: 91,
          tags: ['fragrances', 'perfumes'],
          brand: 'Dior',
          sku: 'E70NB03B',
          weight: 10,
          dimensions: { width: 21.51, height: 7.0, depth: 26.51 },
          warrantyInformation: 'Lifetime warranty',
          availabilityStatus: 'In Stock',
          returnPolicy: '7 days return policy',
          minimumOrderQuantity: 8,
          inStock: true,
          createdAt: '2024-05-23T08:56:21.618Z',
        },
        {
          id: 9,
          title: 'Dolce Shine Eau de',
          category: 'fragrances',
          price: 69.99,
          discountPercentage: 11.47,
          rating: 2.68,
          stock: 3,
          tags: ['fragrances', 'perfumes'],
          brand: 'Dolce & Gabbana',
          sku: '1N046530',
          weight: 5,
          dimensions: { width: 17.0, height: 24.57, depth: 13.3 },
          warrantyInformation: '5 year warranty',
          availabilityStatus: 'Low Stock',
          returnPolicy: '30 days return policy',
          minimumOrderQuantity: 9,
          inStock: true,
          createdAt: '2024-05-23T08:56:21.618Z',
        },
        {
          id: 10,
          title: 'Gucci Bloom Eau de',
          category: 'fragrances',
          price: 79.99,
          discountPercentage: 8.9,
          rating: 4.41,
          stock: 93,
          tags: ['fragrances', 'perfumes'],
          brand: 'Gucci',
          sku: 'FFVO50K0',
          weight: 10,
          dimensions: { width: 22.28, height: 17.81, depth: 27.18 },
          warrantyInformation: 'No warranty',
          availabilityStatus: 'In Stock',
          returnPolicy: 'No return policy',
          minimumOrderQuantity: 10,
          inStock: true,
          createdAt: '2024-05-23T08:56:21.618Z',
        },
      ],
    },
  },
  {
    id: 'users',
    name: 'User Directory',
    description: 'Flat array of user profiles with contact details, company, and roles.',
    path: '$',
    data: [
      {
        id: 101,
        firstName: 'Emma',
        lastName: 'Watson',
        email: 'emma.watson@example.com',
        age: 34,
        role: 'Admin',
        department: 'Engineering',
        active: true,
        salary: 145000,
        startDate: '2021-03-15',
        location: 'San Francisco, CA',
      },
      {
        id: 102,
        firstName: 'Liam',
        lastName: 'Chen',
        email: 'liam.chen@example.com',
        age: 28,
        role: 'Developer',
        department: 'Engineering',
        active: true,
        salary: 115000,
        startDate: '2022-06-01',
        location: 'Seattle, WA',
      },
      {
        id: 103,
        firstName: 'Sophia',
        lastName: 'Rodriguez',
        email: 'sophia.r@example.com',
        age: 31,
        role: 'Product Manager',
        department: 'Product',
        active: true,
        salary: 138000,
        startDate: '2020-11-10',
        location: 'Austin, TX',
      },
      {
        id: 104,
        firstName: 'Noah',
        lastName: 'Kim',
        email: 'noah.kim@example.com',
        age: 26,
        role: 'Designer',
        department: 'Design',
        active: false,
        salary: 95000,
        startDate: '2023-01-20',
        location: 'New York, NY',
      },
      {
        id: 105,
        firstName: 'Olivia',
        lastName: 'Taylor',
        email: 'olivia.t@example.com',
        age: 42,
        role: 'VP of Product',
        department: 'Executive',
        active: true,
        salary: 195000,
        startDate: '2019-04-01',
        location: 'San Francisco, CA',
      },
      {
        id: 106,
        firstName: 'Lucas',
        lastName: 'Müller',
        email: 'lucas.m@example.com',
        age: 37,
        role: 'Data Scientist',
        department: 'AI Research',
        active: true,
        salary: 152000,
        startDate: '2021-08-15',
        location: 'Boston, MA',
      },
      {
        id: 107,
        firstName: 'Ava',
        lastName: 'Patel',
        email: 'ava.patel@example.com',
        age: 29,
        role: 'QA Engineer',
        department: 'Engineering',
        active: true,
        salary: 98000,
        startDate: '2022-09-12',
        location: 'Denver, CO',
      },
      {
        id: 108,
        firstName: 'Ethan',
        lastName: 'Davis',
        email: 'ethan.davis@example.com',
        age: 35,
        role: 'DevOps Lead',
        department: 'Infrastructure',
        active: false,
        salary: 160000,
        startDate: '2020-02-18',
        location: 'Chicago, IL',
      },
    ],
  },
  {
    id: 'crypto',
    name: 'Crypto Market Tickers',
    description: 'Nested crypto market data inside an API payload.',
    path: '$.data.markets',
    data: {
      exchange: 'GlobalCoin',
      timestamp: 1715000000,
      data: {
        totalVolumeUSD: 948271042.85,
        markets: [
          { symbol: 'BTC/USDT', price: 67420.5, volume24h: 31204.1, change24h: 3.42, high24h: 68100.0, low24h: 65120.0, verified: true },
          { symbol: 'ETH/USDT', price: 3480.25, volume24h: 184500.4, change24h: -1.15, high24h: 3560.0, low24h: 3410.0, verified: true },
          { symbol: 'SOL/USDT', price: 174.8, volume24h: 924100.0, change24h: 8.75, high24h: 178.5, low24h: 159.2, verified: true },
          { symbol: 'BNB/USDT', price: 590.1, volume24h: 45210.0, change24h: 0.85, high24h: 598.0, low24h: 582.4, verified: true },
          { symbol: 'XRP/USDT', price: 0.542, volume24h: 42100000.0, change24h: -0.45, high24h: 0.558, low24h: 0.531, verified: false },
          { symbol: 'ADA/USDT', price: 0.485, volume24h: 21800000.0, change24h: 2.1, high24h: 0.495, low24h: 0.472, verified: false },
          { symbol: 'AVAX/USDT', price: 38.4, volume24h: 3400000.0, change24h: 4.8, high24h: 39.2, low24h: 36.1, verified: true },
          { symbol: 'DOT/USDT', price: 7.25, volume24h: 8900000.0, change24h: -2.3, high24h: 7.6, low24h: 7.15, verified: true },
        ],
      },
    },
  },
];
